CREATE TABLE USER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER {
  ID NOT NULL AUTO_INCREMENT,
  USER INT NOT NULL,
  PAYMENT_RIGHT INT NOT NULL DEFAULT (0)
}

CREATE TABLE AUTHORITY (
  ID INT NOT NULL AUTO_INCREMENT,
  USER INT NOT NULL,
  ROLE VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER) REFERENCES USER (ID)
);