CREATE TABLE USER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  USERNAME VARCHAR(45) NOT NULL UNIQUE,
  PASSWORD VARCHAR(60) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  PAYMENT_RIGHT INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_CUST FOREIGN KEY (ID) REFERENCES USER (ID)
);

CREATE TABLE AUTHORITY (
  ID INT NOT NULL AUTO_INCREMENT,
  USER INT NOT NULL,
  ROLE VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_AUTH FOREIGN KEY (USER) REFERENCES USER (ID)
);