CREATE TABLE USER (
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE AUTHORITY (
  ID INT NOT NULL AUTO_INCREMENT,
  USER INT NOT NULL,
  ROLE VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER FOREIGN KEY (USER) REFERENCES USER (ID)
);