INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (1, 'admin', '$2a$10$tJFxnUBhavTa.5DOLXEEIuHENs4ke58NfDS3PMg123mg8dxJN3/He');
INSERT INTO USER (ID, USERNAME, PASSWORD) VALUES (2, 'user', 'user');

INSERT INTO AUTHORITY (ID, USER, ROLE) VALUES (1, 1, 'ROLE_ADMIN');
INSERT INTO AUTHORITY (ID, USER, ROLE) VALUES (2, 1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, USER, ROLE) VALUES (3, 2, 'ROLE_USER');
